### ISSUE TITLE
Update quarto-actions

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#137]
## Update quarto-actions

Following Christophe's example on earthdata-cloud-cookbook. Also do this: 

- [x] SWOT - created a PR for Catalina
- [x] ECOSTRESS
- [x] Cloud Hackathon
- [x] AGU Workshop
- [x] Approach-Guide
- [x] Quarto tutorial

**Comment by jules32** [comment]
Updated the above with the following. Christophe recommended pinning a stable version (the `with` and `version` lines), can revisit after quarto hard release

```
    - name: "Install Quarto"
    - uses: quarto-dev/quarto-actions/install-quarto@main
      with:
        version: 0.9.105
      
    - name: "Quarto render"
      shell: bash
      run: |
        quarto render --execute-debug      
```
